pipeline {
    agent any

    tools {
        jdk 'jdk-17'
        maven 'maven-3.9.6'
    }

    stages {
        stage('checking tools...') {
            steps {
                sh 'java -version'
                sh 'mvn -version'
            }
        }
    }

    stages {
        stage('cleaning workspace...') {
            steps {
                cleanWs()
            }
        }
    }

    stages {
        stage('checkout from scm...') {
            steps {
                git branch: 'main', credentials: 'm41na', url: 'https://github.com/m41na/jenkins-job-dsl.git'
            }
        }
    }

    stages {
        stage('build application...') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
    }

    stages {
        stage('test application...') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
